### PR TITLE
Updating quick submit for case

### PR DESCRIPTION
**Pull request by andreadelrio**
To cover #522
Pending: do the same for `organization` and `method`

### CODE REVIEW

**Comment by dethe** [comment]
Hmm, failed checks looks like it is trying to build native extensions and failing. We have a few Greenskeeper PRs that do that, but I don't see anything here which would break the build. Can you think of anything which would have bumped the version of existing dependencies. I guess Travis might have changed support out from underneath us. I can test if a do-nothing commit based on Master branch breaks too.

**Comment by andreadelrio** [comment]
Before
before_case_quick_submit
before_case_quick_submit2

After
after_case_quick_submit
after_case_quick_submit2

**Comment by andreadelrio** [comment]
@dethe can't think of anything that could be breaking Travis right now :/

**Comment by dethe** [comment]
👍 👍 Thanks!

**Comment by dethe** [comment]
My text-change-only branch also failed to build. Looking at a fix now.

**Comment by dethe** [comment]
@andreadelrio Can you pull from master and see if that fixes the CI issue?

**Pull request merged**
