### PR TITLE
Added videos to Gallery

### PR DESCRIPTION
**Pull request by andreadelrio**
screen shot 2017-07-26 at 11 38 42 pm

To finish covering #499.

### CODE REVIEW

**Comment by jesicarson** [comment]
@andreadelrio The black thumbnails aren't really ideal. Is there a way to have the same thumbnail as the larger image, with a small play button? I'm mainly thinking of the homepage, if say someone only uploads a video and no photo, we'd like a thumbnail image with a play button, not a black box, to show up on the homepage. Does that make sense?

**Comment by andreadelrio** [comment]
@jesicarson can you provide a mockup of how you'd like the thumbnail to appear on the homepage when the case has nothing but 1 video?

**Comment by jesicarson** [comment]
screen shot 2017-07-27 at 1 31 51 pm

@andreadelrio 
50% black overlay
80% white play button (https://material.io/icons/#ic_play_circle_filled)

The question is... when a user clicks the play button, should the video play on the homepage, or should they be taken to the case and have the video play there, larger? I'm wondering what is the most user friendly, open to thoughts here. Thanks!

**Comment by jesicarson** [comment]
@andreadelrio you should also be able to see the video thumbnails in the case entry form and "star" a video to be the featured media item.

**Comment by andreadelrio** [comment]
@jesicarson I'd say let's let them play the video from the homepage. That would also make getting the preview image from the video easier.

I'll need to look into how to get thumbnails from video services (youtube, vimeo, etc) to make videos 'starrable' as well. I'll keep you posted.

**Pull request merged**
