### PR TITLE
Bringing FAB back

### PR DESCRIPTION
**Pull request by andreadelrio**
For mobile: FAB quick-submit is back and we're hiding the Create button from the navbar.

### CODE REVIEW

**Comment by andreadelrio** [comment]
Travis tests are not passing, I already updated snaps on my side.

**Comment by davidascher** [comment]
I don't understand why it's changing the escaping of spaces.

**Comment by davidascher** [comment]
@andreadelrio seems like you've submitted new snapshots which don't match what's happening in CI (and what was happening before).  So, something about your snapshot generation process is different.  Can you make sure you have the right version of Jest installed?

**Comment by andreadelrio** [comment]
Also covers #338 and #339.

**Comment by andreadelrio** [comment]
Also covers #291

**Pull request merged**
